### ISSUE TITLE
Roadmap - Power Bi

### ISSUE THREAD

**Issue by ArthurPedroti** [AGF-Equipamentos/agf-bi#20]
### Melhorias:
- [ ] Filtro por cliente no faturamento

### Projetos:
- [ ] Contas a receber
- [ ] Faturamento por grupo
- [ ] Faturamento por vendedor
- [ ] Gastos por vendedor
- [ ] Recebimento total
- [ ] Recebimento por negócio
- [ ] Perfil de recebimento
- [ ] Perfil de carteira
- [ ] Custos dos negócios
- [ ] Custos pós-vendas
- [ ] Custos frete
- [ ] Custos Marketing
- [ ] Custo pessoal
- [ ] Compras
- [ ] Industrialização
- [ ] Produção
- [ ] Fornecedores Pinhal
- [ ] PCP
- [ ] Frota
- [ ] Painel Gestor
